### ISSUE TITLE
High resource usage?

### ISSUE THREAD

**Issue by albinekb** [daneden/zeitgeist#11] opened 2020-05-20 18:04 UTC
Hi! Thanks for making this, it's really cool.

I have noticed that sometimes after running for a while, it starts eating CPU and memory, causing high energy impact:

![Screenshot 2020-05-20 at 20 01 14](https://user-images.githubusercontent.com/5027156/82480810-a9c18e00-9ad4-11ea-9613-f75d49e64af0.png)

500MB+ RAM while just sitting in the status bar:
![Screenshot 2020-05-20 at 20 01 32](https://user-images.githubusercontent.com/5027156/82480841-b514b980-9ad4-11ea-883b-2b9a3cdfc856.png)

CPU hovering around 10%:
![Screenshot 2020-05-20 at 20 01 47](https://user-images.githubusercontent.com/5027156/82480867-be058b00-9ad4-11ea-852b-728a9f997193.png)

Hardware: 
![Screenshot 2020-05-20 at 20 02 08](https://user-images.githubusercontent.com/5027156/82480902-ca89e380-9ad4-11ea-9165-7cb3dacd4e1e.png)

Since it's native code I would expect lower numbers here, do you know what could be causing this?

**Comment by daneden** [comment] 2020-05-26 10:40
Hey @albinekb! Thanks for reporting; I think I’ve noticed some resource-hogging issues too. I’m not sure what the cause could be off the top of my head other than runaway subprocesses; I’ll try to do some digging and figure out how I can improve things!

**Comment by daneden** [comment] 2020-05-30 19:07
Hey @albinekb! I believe v1.1.3 should resolve at least the majority of performance issues you were encountering. I worked on deferring more work to background threads, reducing timer intervals, and removing redundant class instantiations, which seemed to help reduce the CPU load, especially for long-running sessions! Please let me know if you continue to experience issues, but I’ll optimistically close this issue now!

**Closed by daneden** 2020-05-30 19:07 UTC
